module.exports = [
  { name: 'rank', label: 'Rank' },
  { name: 'title', label: 'Champion' },
  { name: 'role', label: 'Role' },
  { name: 'winPercent', label: 'Win Percent' },
  { name: 'playPercent', label: 'Play Percent' },
  { name: 'banRate', label: 'Ban Rate' },
  { name: 'playerbaseAvgGames', label: 'Playerbase Avg. Games' },
  { name: 'kills', label: 'Kills' },
  { name: 'deaths', label: 'Deaths' },
  { name: 'assists', label: 'Assists' },
  { name: 'largestKillingSpree', label: 'Largest Killing Spree' },
  { name: 'damageDealt', label: 'Damage Dealt' },
  { name: 'damageTaken', label: 'Damage Taken' },
  { name: 'totalHealing', label: 'Total Healing' },
  { name: 'minionsKilled', label: 'Minions Killed' },
  { name: 'enemyJungleCs', label: 'Enemy Jungle CS' },
  { name: 'teamJungleCs', label: 'Team Jungle CS' },
  { name: 'goldEarned', label: 'Gold Earned' },
  { name: 'rolePosition', label: 'Role Position' },
  { name: 'positionChange', label: 'Position Change' },
]